### ISSUE TITLE
can application.yml configure mapUnderscoreToCamelCase and other setting like it?

### ISSUE THREAD

**Issue by tianhao** [mybatis/spring-boot-starter#110]
mybatis-config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN" "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
    <settings>
        <setting name="mapUnderscoreToCamelCase" value="true" />
    </settings>
</configuration>

```

can I move it into application.yml ? like this:
```
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    ...
```
