### ISSUE TITLE
How can i write mapper scan configuration to application.yml ?

### ISSUE THREAD

**Issue by tianhao** [mybatis/spring-boot-starter#120]
My application.yml:
```
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
```
and MybatisConfig:
```
@Configuration
@MapperScan("xxx.*.mapper")
public class MybatisConfig {
}
```

How can i write mapper scan configuration to application.yml ?
If I change my package or add new package, I have to change the MybatisConfig.java file, I prefer to change application.yml.
