### ISSUE TITLE
custom enum typehandler is not working.

### ISSUE THREAD

**Issue by cinabro88** [mybatis/spring-boot-starter#160]
I want to use custom typehandler for write and read my enum.

for example 
``` java
enum OrderChannel {
   PC("1"),
   APP("2"),

  private String code;
  
  public OrderChannel(String code) { this.code = code; }
}
```

When I write CARD(enum value) to database,  I wanna code "1" is written.

this is my typehandler

```java
@MappedTypes(OrderChannel.class)
public class OrderChannelHandler extends EnumTypeHandler<OrderChannel> {

    public OrderChannelHandler(Class<OrderChannel> type) {
        super(type);
    }

    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, OrderChannel parameter, JdbcType jdbcType) throws SQLException {
        ps.setString(i, parameter.getCode());

    }

    @Override
    public OrderChannel getNullableResult(ResultSet rs, String columnName) throws SQLException {
        String code = rs.getString(columnName);
        return OrderChannel.of(code);

    }

    @Override
    public OrderChannel getNullableResult(ResultSet rs, int columnIndex) throws SQLException {
        String code = rs.getString(columnIndex);
        return OrderChannel.of(code);

    }

    @Override
    public OrderChannel getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {
        String code = cs.getString(columnIndex);
        return OrderChannel.of(code);

    }
}
```
and my config.yml
```yml
mybatis:
  mapper-locations: classpath*:**/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    type-handlers-package: com.baemin.order.ruby.constant.typehandler
```

but my typehandler isn't called.

What's a problem??
