### ISSUE TITLE
I can not config my interceptors in application.yml

### ISSUE THREAD

**Issue by ZuiSong** [mybatis/spring-boot-starter#180]
```
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis-conf.xml
  configuration:
    interceptors:
      - cn.mmooo.SqlExplainInterceptor
```
`
***************************
APPLICATION FAILED TO START
***************************

Description:

Binding to target org.mybatis.spring.boot.autoconfigure.MybatisProperties@545e57d7 failed:

    Property: mybatis.configuration.interceptors[0]
    Value: cn.mmooo.SqlExplainInterceptor
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'org.apache.ibatis.plugin.Interceptor' for property 'configuration.interceptors[0]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.apache.ibatis.plugin.Interceptor' for property 'interceptors[0]': no matching editors or conversion strategy found

Action:

Update your application's configuration
`

I can not config my interceptors in application.yml
