### ISSUE TITLE
I can't set a custom ObjectWrapperFactory in application.yml file

### ISSUE THREAD

**Issue by leozhang123** [mybatis/spring-boot-starter#490]
I configration mybatis.configuration.object-wrapper-factory property in yml file :

```
mybatis:
  configuration: 
    map-underscore-to-camel-case: true
    database-id: postgresql 
    object-wrapper-factory: com.MyWrapperFactory
```

But start application is failed ,this error : 

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'mybatis.configuration.object-wrapper-factory' to org.apache.ibatis.reflection.wrapper.ObjectWrapperFactory:

    Property: mybatis.configuration.object-wrapper-factory
    Value: com.MyWrapperFactory
    Origin: class path resource [application.yml]:29:29
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.apache.ibatis.reflection.wrapper.ObjectWrapperFactory]

Action:

Update your application's configuration
```
I use spring boot version is 2.3.3,JDK8 and mybatis-spring-boot-starter 2.1.3
